"""Unified tool implementations facade for Torchlight.

This module re-exports all tool implementations and internal helpers from modular submodules:
- core.tools.fs_tools: File reading, symbols, directory listing, grep, image viewing
- core.tools.edit_engine: Write, edit, diff chunk parser, AST fuzzy matcher, syntax auto-repair
- core.tools.web_tools: Web search, fetch, doc search, Playwright web outcome inspector
- core.tools.system_tools: Shell commands, git operations, memory, task graph, AST search
"""

from __future__ import annotations

# 1. File system & inspection tools
from core.tools.fs_tools import (
    _CTX_WINDOW,
    _MAX_TOOL_OUTPUT,
    _SYM_PATTERNS,
    _extract_symbols,
    _global_memory_mgr,
    _grep_python,
    _grep_rg,
    _read_budget,
    _read_budget_for_ctx,
    _resolve_path,
    _symbol_map,
    _truncate,
    set_ctx_window,
    set_memory_manager,
    tool_grep_impl,
    tool_list_dir_impl,
    tool_read_file_impl,
    tool_read_symbols_impl,
    tool_view_image_impl,
    view_image,
)

# 2. File editing & code quality engine
from core.tools.edit_engine import (
    _REJECT_ON_STUB_DEFAULT,
    _TAB_PRESERVE_BASENAMES,
    _TAB_PRESERVE_EXTS,
    _auto_repair,
    _check_compile,
    _check_syntax,
    _clean_copied_file_text,
    _commit_edit_and_format_result,
    _commit_edit_file,
    _detect_stubs,
    _detect_symptom_patching,
    _detect_truncation_stubs,
    _edit_succeeded,
    _format_code_on_save,
    _get_symbol_bounds_ast,
    _get_symbol_bounds_general,
    _is_test_file,
    _normalize_whitespace,
    _parse_diff_block,
    _reindent_block,
    _strip_leading_filename_header,
    _sync_ast_graph,
    _validate_and_repair,
    tool_edit_file_impl,
    tool_write_file_impl,
)

# 3. Web & documentation tools
from core.tools.web_tools import (
    _DOC_SOURCES,
    _augment_query_with_project_deps,
    _ddg_search,
    _detect_doc_source,
    _extract_identifiers,
    _fetch_remote_playwright,
    _get_browser_headers,
    StructurePreservingHTMLParser,
    tool_doc_search_impl,
    tool_inspect_web_impl,
    tool_web_fetch_impl,
    tool_web_search_impl,
    tool_web_verify_impl,
)

# 4. System, git, memory, and task tools
from core.tools.system_tools import (
    _GIT_DESTRUCTIVE_SUBCOMMANDS,
    _GIT_SAFE_SUBCOMMANDS,
    _GIT_WRITE_SUBCOMMANDS,
    _LONG_CMDS,
    _SAFE_COMMANDS_SET,
    _git_run,
    play_and_verify_game,
    self_improve_game,
    tool_ask_user_impl,
    tool_format_code_impl,
    tool_git_impl,
    tool_play_and_verify_game_impl,
    tool_run_command_impl,
    tool_save_memory_impl,
    tool_search_ast_impl,
    tool_self_improve_game_impl,
    tool_set_phase_impl,
    tool_update_task_graph_impl,
    tool_verify_impl,
)

__all__ = [
    # fs_tools
    "_MAX_TOOL_OUTPUT",
    "_global_memory_mgr",
    "set_memory_manager",
    "_SYM_PATTERNS",
    "_extract_symbols",
    "_symbol_map",
    "_resolve_path",
    "_truncate",
    "_read_budget",
    "_CTX_WINDOW",
    "set_ctx_window",
    "_read_budget_for_ctx",
    "tool_read_file_impl",
    "tool_read_symbols_impl",
    "tool_list_dir_impl",
    "tool_grep_impl",
    "_grep_rg",
    "_grep_python",
    "tool_view_image_impl",
    "view_image",
    # edit_engine
    "_REJECT_ON_STUB_DEFAULT",
    "_TAB_PRESERVE_EXTS",
    "_TAB_PRESERVE_BASENAMES",
    "_normalize_whitespace",
    "_detect_stubs",
    "_format_code_on_save",
    "_check_syntax",
    "_detect_truncation_stubs",
    "_auto_repair",
    "_check_compile",
    "_clean_copied_file_text",
    "_strip_leading_filename_header",
    "_validate_and_repair",
    "_detect_symptom_patching",
    "_is_test_file",
    "_sync_ast_graph",
    "tool_write_file_impl",
    "_edit_succeeded",
    "_parse_diff_block",
    "_get_symbol_bounds_ast",
    "_get_symbol_bounds_general",
    "_commit_edit_file",
    "_commit_edit_and_format_result",
    "_reindent_block",
    "tool_edit_file_impl",
    # web_tools
    "_DOC_SOURCES",
    "_detect_doc_source",
    "_ddg_search",
    "StructurePreservingHTMLParser",
    "_get_browser_headers",
    "_fetch_remote_playwright",
    "_augment_query_with_project_deps",
    "_extract_identifiers",
    "tool_web_search_impl",
    "tool_web_fetch_impl",
    "tool_doc_search_impl",
    "tool_web_verify_impl",
    "tool_inspect_web_impl",
    # system_tools
    "_SAFE_COMMANDS_SET",
    "_LONG_CMDS",
    "tool_run_command_impl",
    "tool_save_memory_impl",
    "tool_update_task_graph_impl",
    "tool_format_code_impl",
    "tool_verify_impl",
    "tool_ask_user_impl",
    "tool_set_phase_impl",
    "_GIT_SAFE_SUBCOMMANDS",
    "_GIT_WRITE_SUBCOMMANDS",
    "_GIT_DESTRUCTIVE_SUBCOMMANDS",
    "_git_run",
    "tool_git_impl",
    "tool_search_ast_impl",
    "tool_play_and_verify_game_impl",
    "play_and_verify_game",
    "tool_self_improve_game_impl",
    "self_improve_game",
]
